### PR TITLE
Adds support for `Boom.someMethod(err)`, closes #138

### LINKED ISSUE #138: Preservation of `err.name` via `Boom.create` or `Boom[someMethod]`
Shouldn't we be preserving the original `err.name`?

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
@arb as I mentioned, I do not call `wrap` directly because it's more convenient and readable to be able to use methods like `Boom.badRequest(err)` instead of `Boom.wrap`.

**Comment by arb** [comment]
I don't think it's more readable. I think it makes the API a little more difficult to read. `wrap` is to wrap an existing error.

**Comment by niftylettuce** [comment]
Oh come on it's another helper method!  I submitted PR it passes all tests
(I even added some).  Do I really need to fork and publish boom of my own
to NPM for something this simple?....  Readable is opinionated.  This just
is a helper method.

**Comment by AdriVanHoudt** [comment]
I could personally see the value of this. Boom is handy so I don't need to remember all the status codes. Making the wrapping easier seems fine to me.

**Comment by arb** [comment]
The threat of forking really does not help your case. If that is what you want to do, I encourage you to do so. 

It's not "adding" anything, it's changing the meaning of  `create`.

I am against this, but if the community supports it, I'll concede.

**Comment by hueniverse** [comment]
I don't mind this change. I think the error should be wrapped first, then set `data`, not the way it is now.

@niftylettuce you should never use forking as an argument for getting a PR merged. Regardless of what was intended, it comes off as an attack on the lead maintainer and it never a productive move.

**Comment by arb** [comment]
@niftylettuce are you still interested in getting this in? Please see my and hueniverse comments. If not, I plan on closing this PR.

**Comment by niftylettuce** [comment]
pushed update without white space

**Comment by arb** [comment]
Please see @hueniverse comment about wrapping first, then setting data.

**Comment by travi** [comment]
i would see this change as valuable as well. anything i can do to contribute to getting this pushed through?

**Comment by travi** [comment]
thank you!

**Comment by niftylettuce** [comment]
woooooooooo!  thank you guys! 🎉  ⚡️ 💥

**Pull request merged**
