### PR TITLE
Accept object or array like error message #189

### PR DESCRIPTION
**Pull request by FelipeBarrosCruz**
Implementation for this issue: #189

### CODE REVIEW

**Comment by Marsup** [comment]
I think you're missing the point. Those are HTTP errors, they *need* a message string. Not to mention that the errors you create are not `Error`s anymore. You are free to attach data like mentioned in the FAQ but IMHO this is wrong.

**Comment by arb** [comment]
Yeah, I don't think this is something we want to be doing with good. In the future, it might be best to wait for some feedback on your issue before following up immediately with a PR. This gives the community and maintainers a place to discuss before a PR.

Secondly, adding new dependencies; development or otherwise isn't taken lightly in the hapijs ecosystem.

**Comment by hueniverse** [comment]
This is a non-starter. You can attach data to errors. Messages are strings.

**Comment by FelipeBarrosCruz** [comment]
Why message only be string?
In the REST RFC don't say must only a string.
Or the proposal of boom is only string?

Payload Semantics: https://tools.ietf.org/html/rfc7231#section-3.3
Another reference Error Handler: https://tools.ietf.org/html/rfc7230#section-2.5

**Comment by hueniverse** [comment]
Because that's how boom is meant to be used. It is a utility on top of `Error`.

**Pull request closed without merging**
