### PR TITLE
Making Boom more Browserify friendly

### PR DESCRIPTION
**Pull request by abritinthebay**
#### What's this PR do?
It adds a MUCH smaller Browserify friendly alternative to pulling in the entire HTTP lib just for the status codes. This isn't a problem in Node but it's a huge lib to shim when running isomorphic apps.

#### Where should the reviewer start?
If you're happy with the construction (it's just the status-code array, as that's all that is used) then it only affects Browserify - node usage is unaffected. Very low impact for most applications.

#### How should this be manually tested?
Try importing the code with Browserify - the file size for the resulting file will be much smaller.

#### Any background context you want to provide?
I've written a Hapi compatible router for an isomorphic application - it required using Call, which uses Boom and Hoek - both have a lot of bloat for browsers (that isn't an issue on the server at all). 
This is an attempt to make the whole package more friendly upstream rather than maintaining a permanent fork.

It will also benefit other users potentially (it's a great lib!) and if there is no plan to use anything other than the status codes perhaps it could be folded into the non-browser side of the lib eventually.

### CODE REVIEW

**Comment by arb** [comment]
Rather than add the complexity of having the browser setting in package.json, just remove the http module entirely and create the array of status codes like you've done? Then you have the same code for node and browser right?

**Comment by abritinthebay** [comment]
I'm fine with that too! Didn't want to shake the boat too much so didn't do that ;) 
But yes - I'll amend the PR and do that.

**Comment by abritinthebay** [comment]
Updated. I used the `internals` object, seemed the logical choice.

**Comment by Marsup** [comment]
Why don't you generate that based on the node object?

**Comment by abritinthebay** [comment]
It is generated based on the node object. It's a direct copy of the Node objects values on my system. Could you clarify what you mean?

**Comment by Marsup** [comment]
It's not generated, it's a copy, if node changes it you won't get the update.

**Comment by abritinthebay** [comment]
Oh I see what you mean. Well the point of the whole PR is to decouple from the very large http module for Browser support. The original commit was just for that but @arb suggested just pulling it in from the array for both - reducing complexity.

In terms of risk - it's almost nil, as the status codes aren't node specified, they are standards. As are the messages. They are extraordinarily unlikely to change.

I'm fine with reverting back to making it a browser only change but there is no risk here. I could add a build step (say an npm script, or grunt task) to build the array from the node code but that seems like needless complexity for something that is almost never going to change.

**Comment by Marsup** [comment]
IIRC io.js has an issue about changing it or adding new codes, so it can change. It can be done by pure browserify.

**Comment by abritinthebay** [comment]
So, just to clarify, you'd prefer I reverted back to the original commit the PR was based on?

**Comment by Marsup** [comment]
The original PR had the same problem.

**Comment by abritinthebay** [comment]
So you want me to add a build script? The entire _point_ of the PR is to not include the http module. As it is unneeded bloat for browsers.

I can write a script that generates the file if that's what you'd prefer, but you'd not helping me solve your issue with this. What would make this acceptable to you so it still removes this problem with the package when included in browserify/webpack/etc?

Leaving the http module is a non-starter for browsers so... do you want a build script to create that file? Because that is the only other option here.

**Comment by Marsup** [comment]
I don't want to create any file, http can be substituted dynamically by a browserify step that would generate the status codes map based on the current node version.

**Comment by abritinthebay** [comment]
Browserify actually already does that - but to do that it shims the *entire http module*. That's the purpose the the `browser` override in the package.json - _as per the browserify docs_.

In other words - this PR is doing exactly what browserify recommends. So... how would you fix this?

Given that shimming the http module specifically is the _recommended_ solution both by you _and_ browserify... what would your alternative be? Leaving the full http shim isn't a solution: it's the problem.

**Comment by Marsup** [comment]
Browserify replaces files by others through configuration, it doesn't allow dynamic things to happen. To do that you need to manipulate the streams that gets into the build.

I'll agree it's a bit more complex and maybe you don't care that the VM you're running on has different messages or more/less status codes. I'll play my card "leave the decision to @arb" as I don't maintain this package :)

**Comment by abritinthebay** [comment]
I guess, given that his suggestion was the "put it in an array" that I can go back to that... but I'd appreciate clarification from @arb on that one.

I know browserify doesn't work that way which is why I was saying you weren't helping ;) The only solutions are the three I've presented - a build step, the original PR (which is the current state), and the modified PR @arb suggested (which I can switch back to).

Again - http status codes should be consistent as they have an RFC spec. If the VM turns them non-spec then that is a bug in the VM. Boom should obviously follow the spec, not the whims of the VM.

**Comment by Marsup** [comment]
Doesn't work which way ? I did on-the-fly modifications of libs through AST parsing (in the browserify bundle), this one is a piece of cake.

**Comment by abritinthebay** [comment]
Sure, I can do it in my bundle. The core problem isn't at my end though - it's in the boom library. 

That's a workaround, not a fix. Difference.

**Comment by abritinthebay** [comment]
Anyhow - I'll wait for @arb to tell me what he'd prefer - given the discussion.

**Comment by hueniverse** [comment]
What's the motivation here? Where is boom used on the client? I assume it's dragged in through some other dependency (since it would be kinda silly client-side module).

**Comment by abritinthebay** [comment]
Writing a router that works isomorphically with Hapi. Hapi requires Call, call requires Boom.

I'm working on Call as we speak ;)

**Comment by hueniverse** [comment]
@abritinthebay doesn't seem worth the effort for this module.

**Comment by abritinthebay** [comment]
Well it's worth the effort in the sense that for the browser it has to pull in the entire http module shim.

So for _for the use case I'm proposing_ it is very much worth it.

**Comment by arb** [comment]
Would dealing with the http module in your own build step solve this?

**Comment by abritinthebay** [comment]
Can't do that - browserify only will allow browser overrides at the package level (ie - Boom would have to do this).

As Boom is imported by Call the only thing I can do is fork Call to replace Boom/Hoek/whatever other package.

Which, honestly, is seeming like the lowest friction method - which is a shame. Boom and Hoek (and Call!) should all be easily browser friendly due to being reasonably self-contained - they just aren't right now. :(

**Comment by hueniverse** [comment]
Honestly, I am getting tired of these efforts to make everything work on the client and server. **hapi.js** is a server side ecosystem and while some components can be used in the browser, I personally don't find that use case at all interesting to accommodate. In the future we are likely to be adding **joi** to the **call** module and elsewhere for function input validation which will bring up all the crap issues people have been complaining about **joi** and it's dependencies.

The right path is to first show that the browser effort is actually worthwhile. Adding this code here because one person has an idea of using the **call** router in the browser doesn't amount to sufficient use case to spend so much time, especially when we are so behind so many other open issues around here.

I say go ahead and fork and see if people actually want to use your new browser-friendly module. If you get traction with it AND new features are added to **call** which you then need to merge to the fork, then I would consider accommodating the browser user case with proven traction.

If this was my call, I would just close this issue for now.

**Comment by arb** [comment]
@abritinthebay thanks for the contribution and engagement in the conversation. This is an area the organization needs clearer direction on and this issue has really helped to get that ball moving. I encourage you to continue the discussion over [here](https://github.com/hapijs/contrib/issues/32). 

While I think the solution you proposed is a good one (it's simple and wouldn't have any impact on Node usage) I worry about what the downstream impacts are of incorporating Browser support. I feel like it would end up being a constant game of catch up that we would all lose.

**Comment by Marsup** [comment]
> Can't do that - wish I could - browserify only will allow browser overrides at the package level (ie - Boom would have to do this at its level for its own imports).

This is wrong, I've already used global transforms for that.

**Comment by abritinthebay** [comment]
> This is wrong, I've already used global transforms for that.

Only if you are replacing the whole package - not just *part* of the package. Which is, naturally, the packages responsibility. I can fork a custom one but honestly that's just saying "well this package author has no interest in being browser friendly" - at which point why would I use their software, let alone fork it?

>  I am getting tired of these efforts to make everything work on the client and server.

That is myopic in the extreme. Isomorphic apps are just going to become more common. Hapi *itself* doesn't have to run in the browser, obviously, but the suite of modules that make it up meet logical needs in the browser (even Boom).

> thanks for the contribution and engagement in the conversation. This is an area the organization needs clearer direction on and this issue has really helped to get that ball moving.

Thanks @arb - I sense a lot of hostility in these responses to a very simple change, but have had none from you. Thanks. It seems philosophical tbh. For me - the browser is just another javascript code platform and compatibility seems like a no brainer when possible.

> While I think the solution you proposed is a good one (it's simple and wouldn't have any impact on Node usage) I worry about what the downstream impacts are of incorporating Browser support. I feel like it would end up being a constant game of catch up that we would all lose.

That'll depend on the project tbh. With Boom? Minimal to none. With others? It'll depend on what it does - but it's reasonably easy to have a policy of "this set of features will always work in the browser" that people can develop against. Not all features will be required on all projects. What features make that list is dependent on the module but it shouldn't be too bad at all (especially not for a module as simple as Boom), it just needs organizational buy-in. I've done similar things on other projects and it just added a few rules around unit tests mostly.

**Pull request closed without merging**
