### PR TITLE
Documented installation and usage

### PR DESCRIPTION
**Pull request by Soviut**

### CODE REVIEW

**Comment by hueniverse** [comment]
Thanks but I'm not going to merge this.

**boom** is part of **hapi** and those learning how to use it rarely show up at a random module they find on npm. They learn about it when the learn how to use **hapi** as a whole.

While you can and welcome to use it with Express, I have no interest in supporting it. The API is well documented already and is one click away from the Readme. I don't see the need to give an intro just so it's on the npm page.

**Comment by Soviut** [comment]
@hueniverse Several articles I've read recently used boom independently and it's jarring to land on a repo that doesn't even have installation instructions (especially since `@hapi/boom` differs greatly from the old `boom` installation).

**Comment by Soviut** [comment]
@Marsup Yes, you do get the deprecation warning but then you're lead to a page that doesn't even explain what the package name is on github. Hence why I'd insist on at least showing `npm install @hapi/boom`. If it's going to be an independent repo, it should meet the bare minimum of documentation to get said repo installed.

**Comment by Marsup** [comment]
The deprecation message contains the new package name.

**Comment by hueniverse** [comment]
@Soviut I can't be held responsible for how other people choose to use this module. It is intended to be used as part of hapi and any other use case is allowed AS-IS and that includes the current state of documentation for those visiting the module's npm page.

I also think your representation of the current state is lacking. The page at https://www.npmjs.com/package/boom clearly points you to https://www.npmjs.com/package/@hapi/boom in the deprecation message. I expect anyone using my open source work to be experienced enough to know how to install scoped modules.

**Comment by Soviut** [comment]
@hueniverse If that's the case, then why does every other node package include an installation example in their readme? I'll update the PR to remove the code example. I'm doing all the work here, so I don't understand the resistance to having your docs improved.

**Comment by hueniverse** [comment]
This is a classic "Jump off a bridge" argument.

There are a lot of things all other modules do that I refuse to. I don't put badges. I don't list node versions in package.json. I use my own lint rules. Etc.

I don't consider your suggestions an improvement. I consider it an anti-pattern that I am purposely not buying into. I want things done a certain way, and in 99% of the time, my actions are purposeful. This is something familiar to anyone using my work as a whole which is why I am taking the time to explain it to you. It is not about me being lazy about adding this info to the readme. I've just spent days writing a 38 pages release notes document for joi. I've been maintaining node modules since node was v0.2. There is a reason to the way I do things and when it is different from the norm, it is because I think the norm is wrong.

**Comment by Soviut** [comment]
There's a build badge right on the page!

image

This isn't "jump off a bridge", it's being a good citizen by taking 2 seconds to show the install line. I could understand you resisting because I was just opening an issue to make the request, but I've done the PR and I'm willing to adjust it to take out the examples, but you didn't even give me a chance.

You've dismissed **real developer experience** feedback claiming that you know better, even when I hit several roadblocks trying to use your package. Rather than complain, I filled in the gaps based on what I learned along the way.

If you don't want contributions or only want to do it "your way", then don't publicize the repo, or lock it, so that people don't make the same "mistake" I did.

**Comment by nijikokun** [comment]
This repository should have installation documentation. It's bitten me in the past.

**Comment by hueniverse** [comment]
I don't know how I can be any clearer. I disagree with how most people manage their open source. I don't go lecture them. I just manage my code the way I want. I took the time to explain to you my position. We do not agree. That's cool. I get the final say. You are free to fork or create your own solution where things will be done your way.

I do not publicize this module. You didn't use it because of anything I wrote. Someone else recommended it. I care deeply about "real developer experience" when it matches the usage patterns I support. In this case, if you were a hapi. user and hit this problem as part of your hapi application, I would look into ways to resolve that problem, probably by improving the documentations that lead you this way.

I don't want developers using my code to use anything on GitHub or npm. I want them to use the official hapi.dev site. That's the developer experience I want to promote and the only one where I am open to improvements (and make them on a daily basis).

I only use the Travis badge and even that one is going away (already started removing it from other hapijs modules). I am moving the entire ecosystem to no longer provide anything meaningful in the Readme and instead point to the developer portal. The API.md file is meant to be consumed by the hapi.dev build process and actually consumed here: https://hapi.dev/family/boom/?v=7.4.3. You can see where this is headed here: https://github.com/hapijs/hapi.

This is all a work in progress. It takes time.

As for your time, I would always advise to open an issue first and ask if a contribution is welcomed before doing the work if the effort in the PR is greater than the effort in asking. Fixing a typo is better in a PR, but changing the project Readme should be an issue first. If you have, I would have told you, like I did other people, that its a change I don't want to make.

I'm locking this thread because there is nothing more to say about this topic.

**Pull request closed without merging**
