### PR TITLE
fix: make reformat configurable in initialize

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
I didn't really see how to write a test for this but let me know if you have ideas.

Fixes https://github.com/hapijs/boom/issues/288

### CODE REVIEW

**Comment by devinivy** [comment]
If you'd like to pull in an old version of boom for testing purposes, you could do something like this: https://github.com/hapijs/hapi/blob/c95985e225fa09c4b640a887ccb4be46dbe265bc/package.json#L43

**Comment by kanongil** [comment]
For a test, I would probably just do something like `Object.defineProperty(new Boom.Boom('oops'), 'reformat', { value: true })`. It should fail on the current release, and pass with this fix.

**Comment by AdriVanHoudt** [comment]
Added the test, thanks for the nice and easy suggestion @kanongil

**Review by kanongil — APPROVED** [review]
LGTM

**Comment by devinivy** [comment]
Thanks!

**Pull request merged**
